development:
  adapter: mysql
  encoding: utf8
  database: snotes_development
  username: root
  password:
  host: localhost

test:
  adapter: mysql
  encoding: utf8
  database: snotes_test
  username: root
  password:
  host: localhost
